
# Host 1 primary dummy Zabbix server
zabbix.hosts[0].name=Zabbix server
zabbix.hosts[0].url=http://localhost:8080/dummy-zabbix/api_jsonrpc.php
zabbix.hosts[0].user=Admin
zabbix.hosts[0].password=zabbix

# Host 2 second dummy host (higher CPU/RAM baseline)
zabbix.hosts[1].name=Ubuntu ohvcloud
zabbix.hosts[1].url=http://localhost:8080/dummy-zabbix-2/api_jsonrpc.php
zabbix.hosts[1].user=Admin
zabbix.hosts[1].password=zabbix

# Host 3 third dummy host (low CPU, high disk, heavy network)
zabbix.hosts[2].name=Fake API
zabbix.hosts[2].url=http://localhost:8080/dummy-zabbix-3/api_jsonrpc.php
zabbix.hosts[2].user=Admin
zabbix.hosts[2].password=zabbix

# Server port
server.port=8080

# Logging
logging.level.org.example=INFO
